install.packages("spdep")
install.packages("tmap")
install.packages("RColorBrewer")
library(spdep)
library(tmap)
library(RColorBrewer)
inout = "E:/EcoApli/Research/Project/Out"
shp= "E:/EcoApli/Research/Project/INGPP/shp"
edos = "E:/EcoApli/Research/Data/GEO/edos"
muns = "E:/EcoApli/Research/Data/GEO/munic"

edos <- readOGR(paste(edos, "ESTADOS.shp", sep="/"), "ESTADOS", stringsAsFactors=F)
muns <- readOGR(paste(muns, "MUNICIPIOS.shp", sep="/"), "MUNICIPIOS", stringsAsFactors=F)
data = read.dta13(paste(inout, "agregada.dta", sep="/"))
tempo=data
tempo$id=data$clave
muns@data$inegi <- paste0(muns@data$CVE_ENT, muns@data$CVE_MUN)
edit(muns$NOM_MUN)
Nombres<-matrix(c("Amacuzac", "Atlatlahucan", "Axochiapan", "Ayala", "Coatlán del Río", 
                  "Cuautla", "Cuernavaca", "Emiliano Zapata", "Huitzilac", "Jantetelco", 
                  "Jiutepec", "Jojutla", "Jonacatepec", "Mazatepec", "Miacatlán", 
                  "Ocuituco", "Puente de Ixtla", "Temixco", "Tepalcingo", "Tepoztlán", 
                  "Tetecala", "Tetela del Volcán", "Tlalnepantla", "Tlaltizapán de Zapata", 
                  "Tlaquiltenango", "Tlayacapan", "Totolapan", "Xochitepec", "Yautepec", 
                  "Yecapixtla", "Zacatepec", "Zacualpan", "Temoac", "Acaponeta", 
                  "Ahuacatlán", "Amatlán de Cañas", "Compostela", "Huajicori", 
                  "Ixtlán del Río", "Jala", "Xalisco", "Del Nayar", "Rosamorada", 
                  "Ruíz", "San Blas", "San Pedro Lagunillas", "Santa María del Oro", 
                  "Santiago Ixcuintla", "Tecuala", "Tepic", "Tuxpan", "La Yesca", 
                  "Bahía de Banderas", "Abasolo", "Agualeguas", "Los Aldamas", 
                  "Allende", "Anáhuac", "Apodaca", "Aramberri", "Bustamante", 
                  "Cadereyta Jiménez", "El Carmen", "Cerralvo", "Ciénega de Flores", 
                  "China", "Doctor Arroyo", "Doctor Coss", "Doctor González", 
                  "Galeana", "García", "San Pedro Garza García", "General Bravo", 
                  "General Escobedo", "General Terán", "General Treviño", "General Zaragoza", 
                  "General Zuazua", "Guadalupe", "Los Herreras", "Higueras", "Hualahuises", 
                  "Iturbide", "Juárez", "Lampazos de Naranjo", "Linares", "Marín", 
                  "Melchor Ocampo", "Mier y Noriega", "Mina", "Montemorelos", "Monterrey", 
                  "Parás", "Pesquería", "Los Ramones", "Rayones", "Sabinas Hidalgo", 
                  "Salinas Victoria", "San Nicolás de los Garza", "Hidalgo", "Santa Catarina", 
                  "Santiago", "Vallecillo", "Villaldama", "Abejones", "Acatlán de Pérez Figueroa", 
                  "Asunción Cacalotepec", "Asunción Cuyotepeji", "Asunción Ixtaltepec", 
                  "Asunción Nochixtlán", "Asunción Ocotlán", "Asunción Tlacolulita", 
                  "Ayotzintepec", "El Barrio de la Soledad", "Calihualá", "Candelaria Loxicha", 
                  "Ciénega de Zimatlán", "Ciudad Ixtepec", "Coatecas Altas", 
                  "Coicoyán de las Flores", "La Compañía", "Concepción Buenavista", 
                  "Concepción Pápalo", "Constancia del Rosario", "Cosolapa", 
                  "Cosoltepec", "Cuilápam de Guerrero", "Cuyamecalco Villa de Zaragoza", 
                  "Chahuites", "Chalcatongo de Hidalgo", "Chiquihuitlán de Benito Juárez", 
                  "Heroica Ciudad de Ejutla de Crespo", "Eloxochitlán de Flores Magón", 
                  "El Espinal", "Tamazulápam del Espíritu Santo", "Fresnillo de Trujano", 
                  "Guadalupe Etla", "Guadalupe de Ramírez", "Guelatao de Juárez", 
                  "Guevea de Humboldt", "Mesones Hidalgo", "Villa Hidalgo", "Heroica Ciudad de Huajuapan de León", 
                  "Huautepec", "Huautla de Jiménez", "Ixtlán de Juárez", "Heroica Ciudad de Juchitán de Zaragoza", 
                  "Loma Bonita", "Magdalena Apasco", "Magdalena Jaltepec", "Santa Magdalena Jicotlán", 
                  "Magdalena Mixtepec", "Magdalena Ocotlán", "Magdalena Peñasco", 
                  "Magdalena Teitipac", "Magdalena Tequisistlán", "Magdalena Tlacotepec", 
                  "Magdalena Zahuatlán", "Mariscala de Juárez", "Mártires de Tacubaya", 
                  "Matías Romero Avendaño", "Mazatlán Villa de Flores", "Miahuatlán de Porfirio Díaz", 
                  "Mixistlán de la Reforma", "Monjas", "Natividad", "Nazareno Etla", 
                  "Nejapa de Madero", "Ixpantepec Nieves", "Santiago Niltepec", 
                  "Oaxaca de Juárez", "Ocotlán de Morelos", "La Pe", "Pinotepa de Don Luis", 
                  "Pluma Hidalgo", "San José del Progreso", "Putla Villa de Guerrero", 
                  "Santa Catarina Quioquitani", "Reforma de Pineda", "La Reforma", 
                  "Reyes Etla", "Rojas de Cuauhtémoc", "Salina Cruz", "San Agustín Amatengo", 
                  "San Agustín Atenango", "San Agustín Chayuco", "San Agustín de las Juntas", 
                  "San Agustín Etla", "San Agustín Loxicha", "San Agustín Tlacotepec", 
                  "San Agustín Yatareni", "San Andrés Cabecera Nueva", "San Andrés Dinicuiti", 
                  "San Andrés Huaxpaltepec", "San Andrés Huayápam", "San Andrés Ixtlahuaca", 
                  "San Andrés Lagunas", "San Andrés Nuxiño", "San Andrés Paxtlán", 
                  "San Andrés Sinaxtla", "San Andrés Solaga", "San Andrés Teotilálpam", 
                  "San Andrés Tepetlapa", "San Andrés Yaá", "San Andrés Zabache", 
                  "San Andrés Zautla", "San Antonino Castillo Velasco", "San Antonino el Alto", 
                  "San Antonino Monte Verde", "San Antonio Acutla", "San Antonio de la Cal", 
                  "San Antonio Huitepec", "San Antonio Nanahuatípam", "San Antonio Sinicahua", 
                  "San Antonio Tepetlapa", "San Baltazar Chichicápam", "San Baltazar Loxicha", 
                  "San Baltazar Yatzachi el Bajo", "San Bartolo Coyotepec", "San Bartolomé Ayautla", 
                  "San Bartolomé Loxicha", "San Bartolomé Quialana", "San Bartolomé Yucuañe", 
                  "San Bartolomé Zoogocho", "San Bartolo Soyaltepec", "San Bartolo Yautepec", 
                  "San Bernardo Mixtepec", "San Blas Atempa", "San Carlos Yautepec", 
                  "San Cristóbal Amatlán", "San Cristóbal Amoltepec", "San Cristóbal Lachirioag", 
                  "San Cristóbal Suchixtlahuaca", "San Dionisio del Mar", "San Dionisio Ocotepec", 
                  "San Dionisio Ocotlán", "San Esteban Atatlahuca", "San Felipe Jalapa de Díaz", 
                  "San Felipe Tejalápam", "San Felipe Usila", "San Francisco Cahuacuá", 
                  "San Francisco Cajonos", "San Francisco Chapulapa", "San Francisco Chindúa", 
                  "San Francisco del Mar", "San Francisco Huehuetlán", "San Francisco Ixhuatán", 
                  "San Francisco Jaltepetongo", "San Francisco Lachigoló", "San Francisco Logueche", 
                  "San Francisco Nuxaño", "San Francisco Ozolotepec", "San Francisco Sola", 
                  "San Francisco Telixtlahuaca", "San Francisco Teopan", "San Francisco Tlapancingo", 
                  "San Gabriel Mixtepec", "San Ildefonso Amatlán", "San Ildefonso Sola", 
                  "San Ildefonso Villa Alta", "San Jacinto Amilpas", "San Jacinto Tlacotepec", 
                  "San Jerónimo Coatlán", "San Jerónimo Silacayoapilla", "San Jerónimo Sosola", 
                  "San Jerónimo Taviche", "San Jerónimo Tecóatl", "San Jorge Nuchita", 
                  "San José Ayuquila", "San José Chiltepec", "San José del Peñasco", 
                  "San José Estancia Grande", "San José Independencia", "San José Lachiguiri", 
                  "San José Tenango", "San Juan Achiutla", "San Juan Atepec", 
                  "Ánimas Trujano", "San Juan Bautista Atatlahuca", "San Juan Bautista Coixtlahuaca", 
                  "San Juan Bautista Cuicatlán", "San Juan Bautista Guelache", 
                  "San Juan Bautista Jayacatlán", "San Juan Bautista Lo de Soto", 
                  "San Juan Bautista Suchitepec", "San Juan Bautista Tlacoatzintepec", 
                  "San Juan Bautista Tlachichilco", "San Juan Bautista Tuxtepec", 
                  "San Juan Cacahuatepec", "San Juan Cieneguilla", "San Juan Coatzóspam", 
                  "San Juan Colorado", "San Juan Comaltepec", "San Juan Cotzocón", 
                  "San Juan Chicomezúchil", "San Juan Chilateca", "San Juan del Estado", 
                  "San Juan del Río", "San Juan Diuxi", "San Juan Evangelista Analco", 
                  "San Juan Guelavía", "San Juan Guichicovi", "San Juan Ihualtepec", 
                  "San Juan Juquila Mixes", "San Juan Juquila Vijanos", "San Juan Lachao", 
                  "San Juan Lachigalla", "San Juan Lajarcia", "San Juan Lalana", 
                  "San Juan de los Cués", "San Juan Mazatlán", "San Juan Mixtepec", 
                  "San Juan Mixtepec", "San Juan Ñumí", "San Juan Ozolotepec", 
                  "San Juan Petlapa", "San Juan Quiahije", "San Juan Quiotepec", 
                  "San Juan Sayultepec", "San Juan Tabaá", "San Juan Tamazola", 
                  "San Juan Teita", "San Juan Teitipac", "San Juan Tepeuxila", 
                  "San Juan Teposcolula", "San Juan Yaeé", "San Juan Yatzona", 
                  "San Juan Yucuita", "San Lorenzo", "San Lorenzo Albarradas", 
                  "San Lorenzo Cacaotepec", "San Lorenzo Cuaunecuiltitla", "San Lorenzo Texmelúcan", 
                  "San Lorenzo Victoria", "San Lucas Camotlán", "San Lucas Ojitlán", 
                  "San Lucas Quiaviní", "San Lucas Zoquiápam", "San Luis Amatlán", 
                  "San Marcial Ozolotepec", "San Marcos Arteaga", "San Martín de los Cansecos", 
                  "San Martín Huamelúlpam", "San Martín Itunyoso", "San Martín Lachilá", 
                  "San Martín Peras", "San Martín Tilcajete", "San Martín Toxpalan", 
                  "San Martín Zacatepec", "San Mateo Cajonos", "Capulálpam de Méndez", 
                  "San Mateo del Mar", "San Mateo Yoloxochitlán", "San Mateo Etlatongo", 
                  "San Mateo Nejápam", "San Mateo Peñasco", "San Mateo Piñas", 
                  "San Mateo Río Hondo", "San Mateo Sindihui", "San Mateo Tlapiltepec", 
                  "San Melchor Betaza", "San Miguel Achiutla", "San Miguel Ahuehuetitlán", 
                  "San Miguel Aloápam", "San Miguel Amatitlán", "San Miguel Amatlán", 
                  "San Miguel Coatlán", "San Miguel Chicahua", "San Miguel Chimalapa", 
                  "San Miguel del Puerto", "San Miguel del Río", "San Miguel Ejutla", 
                  "San Miguel el Grande", "San Miguel Huautla", "San Miguel Mixtepec", 
                  "San Miguel Panixtlahuaca", "San Miguel Peras", "San Miguel Piedras", 
                  "San Miguel Quetzaltepec", "San Miguel Santa Flor", "Villa Sola de Vega", 
                  "San Miguel Soyaltepec", "San Miguel Suchixtepec", "Villa Talea de Castro", 
                  "San Miguel Tecomatlán", "San Miguel Tenango", "San Miguel Tequixtepec", 
                  "San Miguel Tilquiápam", "San Miguel Tlacamama", "San Miguel Tlacotepec", 
                  "San Miguel Tulancingo", "San Miguel Yotao", "San Nicolás", 
                  "San Nicolás Hidalgo", "San Pablo Coatlán", "San Pablo Cuatro Venados", 
                  "San Pablo Etla", "San Pablo Huitzo", "San Pablo Huixtepec", 
                  "San Pablo Macuiltianguis", "San Pablo Tijaltepec", "San Pablo Villa de Mitla", 
                  "San Pablo Yaganiza", "San Pedro Amuzgos", "San Pedro Apóstol", 
                  "San Pedro Atoyac", "San Pedro Cajonos", "San Pedro Coxcaltepec Cántaros", 
                  "San Pedro Comitancillo", "San Pedro el Alto", "San Pedro Huamelula", 
                  "San Pedro Huilotepec", "San Pedro Ixcatlán", "San Pedro Ixtlahuaca", 
                  "San Pedro Jaltepetongo", "San Pedro Jicayán", "San Pedro Jocotipac", 
                  "San Pedro Juchatengo", "San Pedro Mártir", "San Pedro Mártir Quiechapa", 
                  "San Pedro Mártir Yucuxaco", "San Pedro Mixtepec", "San Pedro Mixtepec", 
                  "San Pedro Molinos", "San Pedro Nopala", "San Pedro Ocopetatillo", 
                  "San Pedro Ocotepec", "San Pedro Pochutla", "San Pedro Quiatoni", 
                  "San Pedro Sochiápam", "San Pedro Tapanatepec", "San Pedro Taviche", 
                  "San Pedro Teozacoalco", "San Pedro Teutila", "San Pedro Tidaá", 
                  "San Pedro Topiltepec", "San Pedro Totolápam", "Villa de Tututepec de Melchor Ocampo", 
                  "San Pedro Yaneri", "San Pedro Yólox", "San Pedro y San Pablo Ayutla", 
                  "Villa de Etla", "San Pedro y San Pablo Teposcolula", "San Pedro y San Pablo Tequixtepec", 
                  "San Pedro Yucunama", "San Raymundo Jalpan", "San Sebastián Abasolo", 
                  "San Sebastián Coatlán", "San Sebastián Ixcapa", "San Sebastián Nicananduta", 
                  "San Sebastián Río Hondo", "San Sebastián Tecomaxtlahuaca", 
                  "San Sebastián Teitipac", "San Sebastián Tutla", "San Simón Almolongas", 
                  "San Simón Zahuatlán", "Santa Ana", "Santa Ana Ateixtlahuaca", 
                  "Santa Ana Cuauhtémoc", "Santa Ana del Valle", "Santa Ana Tavela", 
                  "Santa Ana Tlapacoyan", "Santa Ana Yareni", "Santa Ana Zegache", 
                  "Santa Catalina Quierí", "Santa Catarina Cuixtla", "Santa Catarina Ixtepeji", 
                  "Santa Catarina Juquila", "Santa Catarina Lachatao", "Santa Catarina Loxicha", 
                  "Santa Catarina Mechoacán", "Santa Catarina Minas", "Santa Catarina Quiané", 
                  "Santa Catarina Tayata", "Santa Catarina Ticuá", "Santa Catarina Yosonotú", 
                  "Santa Catarina Zapoquila", "Santa Cruz Acatepec", "Santa Cruz Amilpas", 
                  "Santa Cruz de Bravo", "Santa Cruz Itundujia", "Santa Cruz Mixtepec", 
                  "Santa Cruz Nundaco", "Santa Cruz Papalutla", "Santa Cruz Tacache de Mina", 
                  "Santa Cruz Tacahua", "Santa Cruz Tayata", "Santa Cruz Xitla", 
                  "Santa Cruz Xoxocotlán", "Santa Cruz Zenzontepec", "Santa Gertrudis", 
                  "Santa Inés del Monte", "Santa Inés Yatzeche", "Santa Lucía del Camino", 
                  "Santa Lucía Miahuatlán", "Santa Lucía Monteverde", "Santa Lucía Ocotlán", 
                  "Santa María Alotepec", "Santa María Apazco", "Santa María la Asunción", 
                  "Heroica Ciudad de Tlaxiaco", "Ayoquezco de Aldama", "Santa María Atzompa", 
                  "Santa María Camotlán", "Santa María Colotepec", "Santa María Cortijo", 
                  "Santa María Coyotepec", "Santa María Chachoápam", "Villa de Chilapa de Díaz", 
                  "Santa María Chilchotla", "Santa María Chimalapa", "Santa María del Rosario", 
                  "Santa María del Tule", "Santa María Ecatepec", "Santa María Guelacé", 
                  "Santa María Guienagati", "Santa María Huatulco", "Santa María Huazolotitlán", 
                  "Santa María Ipalapa", "Santa María Ixcatlán", "Santa María Jacatepec", 
                  "Santa María Jalapa del Marqués", "Santa María Jaltianguis", 
                  "Santa María Lachixío", "Santa María Mixtequilla", "Santa María Nativitas", 
                  "Santa María Nduayaco", "Santa María Ozolotepec", "Santa María Pápalo", 
                  "Santa María Peñoles", "Santa María Petapa", "Santa María Quiegolani", 
                  "Santa María Sola", "Santa María Tataltepec", "Santa María Tecomavaca", 
                  "Santa María Temaxcalapa", "Santa María Temaxcaltepec", "Santa María Teopoxco", 
                  "Santa María Tepantlali", "Santa María Texcatitlán", "Santa María Tlahuitoltepec", 
                  "Santa María Tlalixtac", "Santa María Tonameca", "Santa María Totolapilla", 
                  "Santa María Xadani", "Santa María Yalina", "Santa María Yavesía", 
                  "Santa María Yolotepec", "Santa María Yosoyúa", "Santa María Yucuhiti", 
                  "Santa María Zacatepec", "Santa María Zaniza", "Santa María Zoquitlán", 
                  "Santiago Amoltepec", "Santiago Apoala", "Santiago Apóstol", 
                  "Santiago Astata", "Santiago Atitlán", "Santiago Ayuquililla", 
                  "Santiago Cacaloxtepec", "Santiago Camotlán", "Santiago Comaltepec", 
                  "Santiago Chazumba", "Santiago Choápam", "Santiago del Río", 
                  "Santiago Huajolotitlán", "Santiago Huauclilla", "Santiago Ihuitlán Plumas", 
                  "Santiago Ixcuintepec", "Santiago Ixtayutla", "Santiago Jamiltepec", 
                  "Santiago Jocotepec", "Santiago Juxtlahuaca", "Santiago Lachiguiri", 
                  "Santiago Lalopa", "Santiago Laollaga", "Santiago Laxopa", "Santiago Llano Grande", 
                  "Santiago Matatlán", "Santiago Miltepec", "Santiago Minas", 
                  "Santiago Nacaltepec", "Santiago Nejapilla", "Santiago Nundiche", 
                  "Santiago Nuyoó", "Santiago Pinotepa Nacional", "Santiago Suchilquitongo", 
                  "Santiago Tamazola", "Santiago Tapextla", "Villa Tejúpam de la Unión", 
                  "Santiago Tenango", "Santiago Tepetlapa", "Santiago Tetepec", 
                  "Santiago Texcalcingo", "Santiago Textitlán", "Santiago Tilantongo", 
                  "Santiago Tillo", "Santiago Tlazoyaltepec", "Santiago Xanica", 
                  "Santiago Xiacuí", "Santiago Yaitepec", "Santiago Yaveo", "Santiago Yolomécatl", 
                  "Santiago Yosondúa", "Santiago Yucuyachi", "Santiago Zacatepec", 
                  "Santiago Zoochila", "Nuevo Zoquiápam", "Santo Domingo Ingenio", 
                  "Santo Domingo Albarradas", "Santo Domingo Armenta", "Santo Domingo Chihuitán", 
                  "Santo Domingo de Morelos", "Santo Domingo Ixcatlán", "Santo Domingo Nuxaá", 
                  "Santo Domingo Ozolotepec", "Santo Domingo Petapa", "Santo Domingo Roayaga", 
                  "Santo Domingo Tehuantepec", "Santo Domingo Teojomulco", "Santo Domingo Tepuxtepec", 
                  "Santo Domingo Tlatayápam", "Santo Domingo Tomaltepec", "Santo Domingo Tonalá", 
                  "Santo Domingo Tonaltepec", "Santo Domingo Xagacía", "Santo Domingo Yanhuitlán", 
                  "Santo Domingo Yodohino", "Santo Domingo Zanatepec", "Santos Reyes Nopala", 
                  "Santos Reyes Pápalo", "Santos Reyes Tepejillo", "Santos Reyes Yucuná", 
                  "Santo Tomás Jalieza", "Santo Tomás Mazaltepec", "Santo Tomás Ocotepec", 
                  "Santo Tomás Tamazulapan", "San Vicente Coatlán", "San Vicente Lachixío", 
                  "San Vicente Nuñú", "Silacayoápam", "Sitio de Xitlapehua", 
                  "Soledad Etla", "Villa de Tamazulápam del Progreso", "Tanetze de Zaragoza", 
                  "Taniche", "Tataltepec de Valdés", "Teococuilco de Marcos Pérez", 
                  "Teotitlán de Flores Magón", "Teotitlán del Valle", "Teotongo", 
                  "Tepelmeme Villa de Morelos", "Heroica Villa Tezoatlán de Segura y Luna, Cuna de la Independencia de Oaxaca", 
                  "San Jerónimo Tlacochahuaya", "Tlacolula de Matamoros", "Tlacotepec Plumas", 
                  "Tlalixtac de Cabrera", "Totontepec Villa de Morelos", "Trinidad Zaachila", 
                  "La Trinidad Vista Hermosa", "Unión Hidalgo", "Valerio Trujano", 
                  "San Juan Bautista Valle Nacional", "Villa Díaz Ordaz", "Yaxe", 
                  "Magdalena Yodocono de Porfirio Díaz", "Yogana", "Yutanduchi de Guerrero", 
                  "Villa de Zaachila", "San Mateo Yucutindoo", "Zapotitlán Lagunas", 
                  "Zapotitlán Palmas", "Santa Inés de Zaragoza", "Zimatlán de Álvarez", 
                  "Caltepec", "Huehuetla", "Huehuetlán el Chico", "Jonotla", "Tecomatlán", 
                  "Zoquiapan", "Acateno", "Ahuatlán", "Ahuehuetitla", "Albino Zertuche", 
                  "Aljojuca", "Amixtlán", "Atempan", "Atzitzihuacán", "Atzitzintla", 
                  "Axutla", "Calpan", "Camocuautla", "Caxhuacan", "Coatzingo", 
                  "Cohuecan", "Coyomeapan", "Coyotepec", "Cuautempan", "Cuautlancingo", 
                  "Cuyoaco", "Chalchicomula de Sesma", "Chapulco", "Chiconcuautla", 
                  "Chignahuapan", "Chignautla", "Chila", "Chila de la Sal", "Chinantla", 
                  "Epatlán", "Esperanza", "Guadalupe", "Guadalupe Victoria", "Huaquechula", 
                  "Huatlatlauca", "Hueytamalco", "Hueytlalpan", "Huitzilan de Serdán", 
                  "Ixcamilpa de Guerrero", "Ixcaquixtla", "Ixtacamaxtitlán", "Jalpan", 
                  "Jopala", "Juan N. Méndez", "Lafragua", "Libres", "La Magdalena Tlatlauquitepec", 
                  "Mixtla", "Molcaxac", "Naupan", "Nicolás Bravo", "Nopalucan", 
                  "Oriental", "Pahuatlán", "Petlalcingo", "Quimixtlán", "San Diego la Mesa Tochimiltzingo", 
                  "San Felipe Teotlalcingo", "San Felipe Tepatlán", "San Jerónimo Tecuanipan", 
                  "San Jerónimo Xayacatlán", "San José Chiapa", "San Juan Atenco", 
                  "San Juan Atzompa", "San Miguel Ixitlán", "San Miguel Xoxtla", 
                  "San Nicolás de los Ranchos", "San Pedro Cholula", "San Pedro Yeloixtlahuaca", 
                  "San Salvador el Seco", "San Salvador el Verde", "Santa Catarina Tlaltempan", 
                  "Santa Inés Ahuatempan", "Santiago Miahuatlán", "Huehuetlán el Grande", 
                  "Soltepec", "Tehuacán", "Tehuitzingo", "Tenampulco", "Teopantlán", 
                  "Tepango de Rodríguez", "Tepemaxalco", "Tepeojuma", "Tepexi de Rodríguez", 
                  "Tepeyahualco", "Tetela de Ocampo", "Teteles de Avila Castillo", 
                  "Teziutlán", "Tianguismanalco", "Tlahuapan", "Tlaltenango", 
                  "Tlanepantla", "Tlapacoya", "Tlapanalá", "Tlaxco", "Totoltepec de Guerrero", 
                  "Tulcingo", "Tuzamapan de Galeana", "Vicente Guerrero", "Xayacatlán de Bravo", 
                  "Xicotepec", "Xicotlán", "Xochiltepec", "Xochitlán de Vicente Suárez", 
                  "Zacapoaxtla", "Zacatlán", "Zaragoza", "Zautla", "Zongozotla", 
                  "Xiutetelco", "Yehualtepec", "Tlacotepec de Benito Juárez", 
                  "Pantepec", "Chietla", "Atoyatempan", "Acatzingo", "Altepexi", 
                  "Coxcatlán", "Quecholac", "Tecamachalco", "Venustiano Carranza", 
                  "Acajete", "General Felipe Ángeles", "San José Miahuatlán", 
                  "Tepanco de López", "Zinacatepec", "Coronango", "Domingo Arenas", 
                  "Tecali de Herrera", "Tochtepec", "Tepatlaxco de Hidalgo", "Acatlán", 
                  "Atlixco", "Palmar de Bravo", "Rafael Lara Grajales", "Acteopan", 
                  "Ahuacatlán", "Ahuazotepec", "Aquixtla", "Atexcal", "Atzala", 
                  "Ayotoxco de Guerrero", "Coatepec", "Cohetzala", "Cuapiaxtla de Madero", 
                  "Cuautinchán", "Cuayuca de Andrade", "Cuetzalan del Progreso", 
                  "Chichiquila", "Chigmecatitlán", "Honey", "Chilchotla", "Eloxochitlán", 
                  "Hermenegildo Galeana", "Huauchinango", "Huejotzingo", "Hueyapan", 
                  "Atlequizayan", "Ixtepec", "Jolalpan", "Juan Galindo", "Mazapiltepec de Juárez", 
                  "Cañada Morelos", "Nauzontla", "Ocotepec", "Olintla", "Piaxtla", 
                  "Los Reyes de Juárez", "San Antonio Cañada", "San Gregorio Atzompa", 
                  "San Pablo Anicano", "San Gabriel Chilac", "San Martín Totoltepec", 
                  "San Matías Tlalancaleca", "San Nicolás Buenos Aires", "San Sebastián Tlacotepec", 
                  "Santa Isabel Cholula", "Santo Tomás Hueyotlipan", "Teotlalco", 
                  "Tepetzintla", "Tepexco", "Tepeyahualco de Cuauhtémoc", "Tilapa", 
                  "Tlacuilotepec", "Tlachichuca", "Tlaola", "Tlatlauquitepec", 
                  "Tochimilco", "Tzicatlacoyan", "Xochiapulco", "Xochitlán Todos Santos", 
                  "Yaonáhuac", "Zacapala", "Zapotitlán", "Zapotitlán de Méndez", 
                  "Zihuateutla", "Tepeaca", "San Salvador Huixcolotla", "Izúcar de Matamoros", 
                  "Francisco Z. Mena", "Nealtican", "Chiautla", "Amozoc", "Ocoyucan", 
                  "Ajalpan", "Juan C. Bonilla", "Huitziltepec", "Zoquitlán", "San Martín Texmelucan", 
                  "Chiautzingo", "Puebla", "San Andrés Cholula", "Tequisquiapan", 
                  "Arroyo Seco", "San Juan del Río", "Huimilpan", "Jalpan de Serra", 
                  "Pedro Escobedo", "Corregidora", "Landa de Matamoros", "Pinal de Amoles", 
                  "Cadereyta de Montes", "Amealco de Bonfil", "San Joaquín", "Peñamiller", 
                  "Tolimán", "Colón", "Ezequiel Montes", "El Marqués", "Querétaro", 
                  "Cozumel", "Felipe Carrillo Puerto", "Isla Mujeres", "Othón P. Blanco", 
                  "Benito Juárez", "José María Morelos", "Lázaro Cárdenas", 
                  "Solidaridad", "Tulum", "Bacalar", "El Naranjo", "Matlapa", "Villa de Arista", 
                  "Zaragoza", "Xilitla", "Axtla de Terrazas", "Villa Juárez", 
                  "Tamuín", "Tampacán", "Villa de Guadalupe", "Villa de Arriaga", 
                  "Tanlajás", "Tamazunchale", "Venado", "Vanegas", "Villa Hidalgo", 
                  "Tierra Nueva", "Tampamolón Corona", "Villa de Reyes", "Villa de Ramos", 
                  "Villa de la Paz", "Tanquián de Escobedo", "Mexquitic de Carmona", 
                  "Matehuala", "Soledad de Graciano Sánchez", "Santo Domingo", 
                  "Lagunillas", "Huehuetlán", "Aquismón", "San Vicente Tancuayalab", 
                  "Guadalcázar", "Ebano", "Santa María del Río", "Charcas", 
                  "Coxcatlán", "Santa Catarina", "San Nicolás Tolentino", "Ciudad Valles", 
                  "Tancanhuitz", "Ciudad Fernández", "Ciudad del Maíz", "Cerro de San Pedro", 
                  "San Martín Chalchicuautla", "Cerritos", "Cedral", "Catorce", 
                  "San Luis Potosí", "Cárdenas", "Armadillo de los Infante", 
                  "San Ciro de Acosta", "San Antonio", "Salinas", "Rioverde", "Alaquines", 
                  "Ahualulco", "Rayón", "Moctezuma", "Tamasopo", "Sinaloa", "Mazatlán", 
                  "Ahome", "El Fuerte", "Guasave", "Badiraguato", "Concordia", 
                  "Mocorito", "Rosario", "Cosalá", "Choix", "Salvador Alvarado", 
                  "San Ignacio", "Navolato", "Elota", "Culiacán", "Escuinapa", 
                  "Angostura", "San Ignacio Río Muerto", "Benito Juárez", "Opodepe", 
                  "Onavas", "Nogales", "Nacozari de García", "Naco", "General Plutarco Elías Calles", 
                  "Villa Hidalgo", "Ures", "Tubutama", "Nácori Chico", "Moctezuma", 
                  "Mazatán", "Yécora", "Tepache", "Magdalena", "Imuris", "Huépac", 
                  "Huachinera", "Trincheras", "Suaqui Grande", "Villa Pesqueira", 
                  "Granados", "Fronteras", "Soyopa", "Sáric", "Santa Cruz", "Empalme", 
                  "Santa Ana", "San Pedro de la Cueva", "Etchojoa", "Divisaderos", 
                  "Cumpas", "Cucurpe", "San Miguel de Horcasitas", "San Javier", 
                  "San Felipe de Jesús", "Sahuaripa", "Navojoa", "La Colorada", 
                  "Carbó", "Cananea", "Baviácora", "Bácum", "Rosario", "Huatabampo", 
                  "Cajeme", "Benjamín Hill", "Huásabas", "Bavispe", "San Luis Río Colorado", 
                  "Guaymas", "Hermosillo", "Banámichi", "Bacoachi", "Bacerac", 
                  "Bacanora", "Puerto Peñasco", "Bacadéhuachi", "Atil", "Arizpe", 
                  "Arivechi", "Aconchi", "Caborca", "Rayón", "Quiriego", "Altar", 
                  "Alamos", "Pitiquito", "Oquitoa", "Agua Prieta", "Balancán", 
                  "Cárdenas", "Centla", "Centro", "Comalcalco", "Cunduacán", 
                  "Emiliano Zapata", "Huimanguillo", "Jalapa", "Jalpa de Méndez", 
                  "Jonuta", "Macuspana", "Nacajuca", "Paraíso", "Tacotalpa", "Teapa", 
                  "Tenosique", "Tlaxcala", "Chiautempan", "Hueyotlipan", "Tlaxco", 
                  "Tocatlán", "Apetatitlán de Antonio Carvajal", "Ixtacuixtla de Mariano Matamoros", 
                  "Ixtenco", "Tepetitla de Lardizábal", "Panotla", "Totolac", 
                  "Ziltlaltépec de Trinidad Sánchez Santos", "Atlangatepec", 
                  "Mazatecochco de José María Morelos", "Tzompantepec", "Atltzayanca", 
                  "Contla de Juan Cuamatzi", "Teolocholco", "Xaloztoc", "Xaltocan", 
                  "Apizaco", "Nanacamilpa de Mariano Arista", "Calpulalpan", "Acuamanala de Miguel Hidalgo", 
                  "Terrenate", "Lázaro Cárdenas", "La Magdalena Tlaltelulco", 
                  "El Carmen Tequexquitla", "Natívitas", "San Pablo del Monte", 
                  "Tetla de la Solidaridad", "Santa Cruz Quilehtla", "Santa Isabel Xiloxoxtla", 
                  "Cuapiaxtla", "Papalotla de Xicohténcatl", "Xicohtzinco", "Cuaxomulco", 
                  "Santa Cruz Tlaxcala", "Tenancingo", "San Damián Texóloc", 
                  "San Jerónimo Zacualpan", "San Juan Huactzinco", "San Lorenzo Axocomanitla", 
                  "San Francisco Tetlanohcan", "Muñoz de Domingo Arenas", "Tepeyanco", 
                  "Yauhquemehcan", "Zacatelco", "San José Teacalco", "San Lucas Tecopilco", 
                  "Españita", "Santa Ana Nopalucan", "Santa Apolonia Teacalco", 
                  "Santa Catarina Ayometla", "Tetlatlahuca", "Benito Juárez", 
                  "Emiliano Zapata", "Huamantla", "Sanctórum de Lázaro Cárdenas", 
                  "Amaxac de Guerrero", "Abasolo", "Aldama", "Altamira", "Antiguo Morelos", 
                  "Burgos", "Bustamante", "Camargo", "Casas", "Ciudad Madero", 
                  "Cruillas", "Gómez Farías", "González", "Güémez", "Guerrero", 
                  "Gustavo Díaz Ordaz", "Hidalgo", "Jaumave", "Jiménez", "Llera", 
                  "Mainero", "El Mante", "Matamoros", "Méndez", "Mier", "Miguel Alemán", 
                  "Miquihuana", "Nuevo Laredo", "Nuevo Morelos", "Ocampo", "Padilla", 
                  "Palmillas", "Reynosa", "Río Bravo", "San Carlos", "San Fernando", 
                  "San Nicolás", "Soto la Marina", "Tampico", "Tula", "Valle Hermoso", 
                  "Victoria", "Villagrán", "Xicoténcatl", "Acajete", "Acatlán", 
                  "Actopan", "Acultzingo", "Camarón de Tejeda", "Alpatláhuac", 
                  "Altotonga", "Alvarado", "Amatitlán", "Amatlán de los Reyes", 
                  "Angel R. Cabada", "Apazapan", "Aquila", "Astacinga", "Atoyac", 
                  "Atzacan", "Ayahualulco", "Banderilla", "Benito Juárez", "Calcahualco", 
                  "Camerino Z. Mendoza", "Carrillo Puerto", "Catemaco", "Cerro Azul", 
                  "Citlaltépetl", "Coatzacoalcos", "Coatzintla", "Coetzala", "Comapa", 
                  "Córdoba", "Cosautlán de Carvajal", "Cotaxtla", "Coxquihui", 
                  "Cuichapa", "Cuitláhuac", "Chacaltianguis", "Chiconamel", "Chiconquiaco", 
                  "Chicontepec", "Las Choapas", "Chocamán", "Chumatlán", "Emiliano Zapata", 
                  "Filomeno Mata", "Fortín", "Gutiérrez Zamora", "Huatusco", 
                  "Huayacocotla", "Hueyapan de Ocampo", "Isla", "Ixcatepec", "Ixhuacán de los Reyes", 
                  "Ixhuatlancillo", "Ixhuatlán del Sureste", "Ixhuatlán de Madero", 
                  "Ixmatlahuacan", "Jalacingo", "Xalapa", "Jáltipan", "Jesús Carranza", 
                  "Jilotepec", "Juchique de Ferrer", "Landero y Coss", "Lerdo de Tejada", 
                  "Mariano Escobedo", "Martínez de la Torre", "Medellín", "Miahuatlán", 
                  "Las Minas", "Misantla", "Moloacán", "Naranjal", "Nautla", "Nogales", 
                  "Omealca", "Orizaba", "Ozuluama de Mascareñas", "Pajapan", "Papantla", 
                  "Paso de Ovejas", "Perote", "Playa Vicente", "Las Vigas de Ramírez", 
                  "Pueblo Viejo", "Puente Nacional", "Rafael Delgado", "Río Blanco", 
                  "Saltabarranca", "San Andrés Tenejapan", "San Juan Evangelista", 
                  "Santiago Tuxtla", "Sayula de Alemán", "Soconusco", "Soledad de Doblado", 
                  "Soteapan", "Tamiahua", "Tampico Alto", "Tancoco", "Tantoyuca", 
                  "Tecolutla", "Tehuipango", "Tempoal", "Tenochtitlán", "Teocelo", 
                  "Tepatlaxco", "Tepetzintla", "Tequila", "José Azueta", "Tezonapa", 
                  "Tihuatlán", "Tlacojalpan", "Tlacolulan", "Tlacotalpan", "Tlalixcoyan", 
                  "Tlalnelhuayocan", "Tlilapan", "Tomatlán", "Tonayán", "Tuxpan", 
                  "Tuxtilla", "Ursulo Galván", "Veracruz", "Xoxocotla", "Yanga", 
                  "Zacualpan", "Zaragoza", "Zentla", "Zontecomatlán de López y Fuentes", 
                  "Zozocolco de Hidalgo", "Agua Dulce", "Tres Valles", "Uxpanapa", 
                  "San Rafael", "Santiago Sochiapan", "Acayucan", "Acula", "Alto Lucero de Gutiérrez Barrios", 
                  "Naranjos Amatlán", "La Antigua", "Atlahuilco", "Atzalan", "Tlaltetela", 
                  "Boca del Río", "Cazones de Herrera", "Mecatlán", "Mecayapan", 
                  "Minatitlán", "Mixtla de Altamirano", "Naolinco", "Oluta", "Otatitlán", 
                  "Oteapan", "Pánuco", "Paso del Macho", "La Perla", "Platón Sánchez", 
                  "Poza Rica de Hidalgo", "Rafael Lucio", "Los Reyes", "San Andrés Tuxtla", 
                  "Sochiapa", "Soledad Atzompa", "Tamalín", "Tantima", "Tatatila", 
                  "Castillo de Teayo", "Álamo Temapache", "Tenampa", "Tepetlán", 
                  "Texcatepec", "Texhuacán", "Texistepec", "Tierra Blanca", "Tlacotepec de Mejía", 
                  "Tlachichilco", "Tlapacoyan", "Tlaquilpa", "Totutla", "Vega de Alatorre", 
                  "Villa Aldama", "Yecuatla", "Zongolica", "El Higo", "Nanchital de Lázaro Cárdenas del Río", 
                  "Tatahuicapan de Juárez", "Coacoatzintla", "Coahuitlán", "Coatepec", 
                  "Colipa", "Coscomatepec", "Cosoleacaque", "Coyutla", "Chalma", 
                  "Chinameca", "Chinampa de Gorostiza", "Chontla", "Espinal", "Hidalgotitlán", 
                  "Huiloapan de Cuauhtémoc", "Ignacio de la Llave", "Ilamatlán", 
                  "Ixhuatlán del Café", "Ixtaczoquitlán", "Jalcomulco", "Jamapa", 
                  "Xico", "Juan Rodríguez Clara", "Magdalena", "Maltrata", "Manlio Fabio Altamirano", 
                  "Carlos A. Carrillo", "Cosamaloapan de Carpio", "Maxcanú", "Kopomá", 
                  "Kinchil", "Chichimilá", "Chocholá", "Sotuta", "Sinanché", 
                  "Seyé", "Santa Elena", "San Felipe", "Sanahcat", "Samahil", 
                  "Río Lagartos", "Quintana Roo", "Peto", "Panabá", "Opichén", 
                  "Muxupip", "Muna", "Mocochá", "Mayapán", "Buctzotz", "Bokobá", 
                  "Baca", "Akil", "Acanceh", "Abalá", "Kaua", "Tizimín", "Tixpéhual", 
                  "Halachó", "Motul", "Mérida", "Kantunil", "Tixmehuac", "Tixkokob", 
                  "Kanasín", "Umán", "Izamal", "Ixil", "Tixcacalcupul", "Hunucmá", 
                  "Huhí", "Hoctún", "Tinum", "Timucuy", "Cuzamá", "Homún", 
                  "Hocabá", "Dzoncauich", "Ticul", "Teya", "Tetiz", "Sacalum", 
                  "Oxkutzcab", "Espita", "Chumayel", "Tepakán", "Maní", "Telchac Puerto", 
                  "Dzitás", "Dzilam González", "Dzilam de Bravo", "Progreso", 
                  "Dzidzantún", "Dzemul", "Dzán", "Temozón", "Temax", "Telchac Pueblo", 
                  "Chikindzonot", "Chicxulub Pueblo", "Chemax", "Tekom", "Tekax", 
                  "Tekantó", "Tekal de Venegas", "Chapab", "Chankom", "Chacsinkín", 
                  "Yobaín", "Yaxkukul", "Xocchel", "Tecoh", "Teabo", "Tahmek", 
                  "Tahdziú", "Yaxcabá", "Valladolid", "Ucú", "Suma", "Sudzal", 
                  "Celestún", "Sucilá", "Cuncunul", "Conkal", "Mama", "Tekit", 
                  "Uayma", "Cenotillo", "Cantamayec", "Cansahcab", "Tzucacab", 
                  "Tunkás", "Calotmul", "Cacalchén", "Apozol", "Apulco", "Atolinga", 
                  "Benito Juárez", "Calera", "Cañitas de Felipe Pescador", "Concepción del Oro", 
                  "Cuauhtémoc", "Chalchihuites", "Fresnillo", "Trinidad García de la Cadena", 
                  "Genaro Codina", "General Enrique Estrada", "General Francisco R. Murguía", 
                  "El Plateado de Joaquín Amaro", "General Pánfilo Natera", "Guadalupe", 
                  "Huanusco", "Jalpa", "Jerez", "Jiménez del Teul", "Juan Aldama", 
                  "Juchipila", "Loreto", "Luis Moya", "Mazapil", "Melchor Ocampo", 
                  "Mezquital del Oro", "Miguel Auza", "Momax", "Monte Escobedo", 
                  "Morelos", "Moyahua de Estrada", "Nochistlán de Mejía", "Noria de Ángeles", 
                  "Ojocaliente", "Pánuco", "Pinos", "Río Grande", "Sain Alto", 
                  "El Salvador", "Sombrerete", "Susticacán", "Tabasco", "Tepechitlán", 
                  "Tepetongo", "Teúl de González Ortega", "Tlaltenango de Sánchez Román", 
                  "Valparaíso", "Vetagrande", "Villa de Cos", "Villa García", 
                  "Villa González Ortega", "Villa Hidalgo", "Villanueva", "Zacatecas", 
                  "Trancoso", "Santa María de la Paz", "Aguascalientes", "Asientos", 
                  "Calvillo", "Cosío", "Jesús María", "Pabellón de Arteaga", 
                  "Rincón de Romos", "San José de Gracia", "Tepezalá", "El Llano", 
                  "San Francisco de los Romo", "Playas de Rosarito", "Mexicali", 
                  "Tecate", "Ensenada", "Tijuana", "Loreto", "Mulegé", "Comondú", 
                  "La Paz", "Los Cabos", "Campeche", "Carmen", "Champotón", "Palizada", 
                  "Calkiní", "Candelaria", "Calakmul", "Hopelchén", "Hecelchakán", 
                  "Escárcega", "Tenabo", "Abasolo", "Acuña", "Allende", "Arteaga", 
                  "Candela", "Castaños", "Cuatro Ciénegas", "Escobedo", "Francisco I. Madero", 
                  "Frontera", "General Cepeda", "Guerrero", "Hidalgo", "Jiménez", 
                  "Juárez", "Lamadrid", "Matamoros", "Monclova", "Morelos", "Múzquiz", 
                  "Nadadores", "Nava", "Ocampo", "Parras", "Piedras Negras", "Progreso", 
                  "Ramos Arizpe", "Sabinas", "Sacramento", "Saltillo", "San Buenaventura", 
                  "San Juan de Sabinas", "San Pedro", "Sierra Mojada", "Torreón", 
                  "Viesca", "Villa Unión", "Zaragoza", "Armería", "Colima", "Comala", 
                  "Coquimatlán", "Cuauhtémoc", "Ixtlahuacán", "Manzanillo", 
                  "Minatitlán", "Tecomán", "Villa de Álvarez", "Acacoyagua", 
                  "Acala", "Acapetahua", "Altamirano", "Amatán", "Amatenango de la Frontera", 
                  "Amatenango del Valle", "Angel Albino Corzo", "Arriaga", "Bejucal de Ocampo", 
                  "Bella Vista", "Berriozábal", "Bochil", "El Bosque", "Cacahoatán", 
                  "Catazajá", "Cintalapa", "Coapilla", "Comitán de Domínguez", 
                  "La Concordia", "Copainalá", "Chalchihuitán", "Chamula", "Chanal", 
                  "Chapultenango", "Chenalhó", "Chiapa de Corzo", "Chiapilla", 
                  "Chicoasén", "Chicomuselo", "Chilón", "Escuintla", "Francisco León", 
                  "Frontera Comalapa", "Frontera Hidalgo", "La Grandeza", "Huehuetán", 
                  "Huixtán", "Huitiupán", "Huixtla", "La Independencia", "Ixhuatán", 
                  "Ixtacomitán", "Ixtapa", "Ixtapangajoya", "Jiquipilas", "Jitotol", 
                  "Juárez", "Larráinzar", "La Libertad", "Mapastepec", "Las Margaritas", 
                  "Mazapa de Madero", "Mazatán", "Metapa", "Mitontic", "Motozintla", 
                  "Nicolás Ruíz", "Ocosingo", "Ocotepec", "Ocozocoautla de Espinosa", 
                  "Ostuacán", "Osumacinta", "Oxchuc", "Palenque", "Pantelhó", 
                  "Pantepec", "Pichucalco", "Pijijiapan", "El Porvenir", "Villa Comaltitlán", 
                  "Pueblo Nuevo Solistahuacán", "Rayón", "Reforma", "Las Rosas", 
                  "Sabanilla", "Salto de Agua", "San Cristóbal de las Casas", 
                  "San Fernando", "Siltepec", "Simojovel", "Sitalá", "Socoltenango", 
                  "Solosuchiapa", "Soyaló", "Suchiapa", "Suchiate", "Sunuapa", 
                  "Tapachula", "Tapalapa", "Tapilula", "Tecpatán", "Tenejapa", 
                  "Teopisca", "Tila", "Tonalá", "Totolapa", "La Trinitaria", "Tumbalá", 
                  "Tuxtla Gutiérrez", "Tuxtla Chico", "Tuzantán", "Tzimol", "Unión Juárez", 
                  "Venustiano Carranza", "Villa Corzo", "Villaflores", "Yajalón", 
                  "San Lucas", "Zinacantán", "San Juan Cancuc", "Aldama", "Benemérito de las Américas", 
                  "Maravilla Tenejapa", "Marqués de Comillas", "Montecristo de Guerrero", 
                  "San Andrés Duraznal", "Santiago el Pinar", "Ahumada", "Aldama", 
                  "Allende", "Aquiles Serdán", "Ascensión", "Bachíniva", "Balleza", 
                  "Batopilas", "Bocoyna", "Buenaventura", "Camargo", "Carichí", 
                  "Casas Grandes", "Coronado", "Coyame del Sotol", "La Cruz", "Cuauhtémoc", 
                  "Cusihuiriachi", "Chihuahua", "Chínipas", "Delicias", "Dr. Belisario Domínguez", 
                  "Galeana", "Santa Isabel", "Gómez Farías", "Gran Morelos", 
                  "Guachochi", "Guadalupe", "Guadalupe y Calvo", "Guazapares", 
                  "Guerrero", "Hidalgo del Parral", "Huejotitán", "Ignacio Zaragoza", 
                  "Janos", "Jiménez", "Juárez", "Julimes", "López", "Madera", 
                  "Maguarichi", "Manuel Benavides", "Matachí", "Matamoros", "Meoqui", 
                  "Morelos", "Moris", "Namiquipa", "Nonoava", "Nuevo Casas Grandes", 
                  "Ocampo", "Ojinaga", "Praxedis G. Guerrero", "Riva Palacio", 
                  "Rosales", "Rosario", "San Francisco de Borja", "San Francisco de Conchos", 
                  "San Francisco del Oro", "Santa Bárbara", "Satevó", "Saucillo", 
                  "Temósachic", "El Tule", "Urique", "Uruachi", "Valle de Zaragoza", 
                  "Azcapotzalco", "Coyoacán", "Cuajimalpa de Morelos", "Gustavo A. Madero", 
                  "Iztacalco", "Iztapalapa", "La Magdalena Contreras", "Milpa Alta", 
                  "Álvaro Obregón", "Tláhuac", "Tlalpan", "Xochimilco", "Benito Juárez", 
                  "Cuauhtémoc", "Miguel Hidalgo", "Venustiano Carranza", "Canatlán", 
                  "Canelas", "Coneto de Comonfort", "Cuencamé", "Durango", "General Simón Bolívar", 
                  "Gómez Palacio", "Guadalupe Victoria", "Guanaceví", "Hidalgo", 
                  "Indé", "Lerdo", "Mapimí", "Mezquital", "Nazas", "Nombre de Dios", 
                  "Ocampo", "El Oro", "Otáez", "Pánuco de Coronado", "Peñón Blanco", 
                  "Poanas", "Pueblo Nuevo", "Rodeo", "San Bernardo", "San Dimas", 
                  "San Juan de Guadalupe", "San Juan del Río", "San Luis del Cordero", 
                  "San Pedro del Gallo", "Santa Clara", "Santiago Papasquiaro", 
                  "Súchil", "Tamazula", "Tepehuanes", "Tlahualilo", "Topia", "Vicente Guerrero", 
                  "Nuevo Ideal", "Salvatierra", "Celaya", "San José Iturbide", 
                  "Pueblo Nuevo", "Santiago Maravatío", "Purísima del Rincón", 
                  "San Felipe", "Apaseo el Alto", "Apaseo el Grande", "Yuriria", 
                  "Jerécuaro", "Xichú", "Doctor Mora", "Santa Catarina", "Tarandacuao", 
                  "Tierra Blanca", "Tarimoro", "Uriangato", "Coroneo", "Victoria", 
                  "Atarjea", "Cortazar", "Acámbaro", "Comonfort", "Irapuato", 
                  "Romita", "Silao de la Victoria", "Abasolo", "Dolores Hidalgo Cuna de la Independencia Nacional", 
                  "San Miguel de Allende", "San Francisco del Rincón", "Huanímaro", 
                  "San Diego de la Unión", "Jaral del Progreso", "Manuel Doblado", 
                  "Villagrán", "Cuerámaro", "Guanajuato", "León", "Santa Cruz de Juventino Rosas", 
                  "Ocampo", "Valle de Santiago", "San Luis de la Paz", "Pénjamo", 
                  "Salamanca", "Moroleón", "Apaxtla", "Cuetzala del Progreso", 
                  "Chilapa de Álvarez", "General Canuto A. Neri", "General Heliodoro Castillo", 
                  "Huitzuco de los Figueroa", "Juan R. Escudero", "Leonardo Bravo", 
                  "Quechultenango", "San Marcos", "Tecoanapa", "Teloloapan", "Tixtla de Guerrero", 
                  "Zitlala", "Eduardo Neri", "Iguala de la Independencia", "Atenango del Río", 
                  "Atlamajalcingo del Monte", "Atlixtac", "Azoyú", "Copala", "Copalillo", 
                  "Copanatoyac", "Cuautepec", "Malinaltepec", "Olinalá", "Ometepec", 
                  "Tlacoapa", "Tlapa de Comonfort", "Xalpatláhuac", "Xochihuehuetlán", 
                  "Zapotitlán Tablas", "Marquelia", "Juchitán", "Cuajinicuilapa", 
                  "Tlacoachistlahuaca", "Tlalixtaquilla de Maldonado", "Metlatónoc", 
                  "Cochoapa el Grande", "Petatlán", "Ajuchitlán del Progreso", 
                  "Atoyac de Álvarez", "Benito Juárez", "Coahuayutla de José María Izazaga", 
                  "Técpan de Galeana", "Tlalchapa", "Zirándaro", "La Unión de Isidoro Montes de Oca", 
                  "Ixcateopan de Cuauhtémoc", "Pedro Ascencio Alquisiras", "Tetipac", 
                  "Taxco de Alarcón", "Buenavista de Cuéllar", "Acapulco de Juárez", 
                  "Cocula", "Chilpancingo de los Bravo", "Mártir de Cuilapan", 
                  "Tepecoacuilco de Trujano", "Alpoyeca", "Ayutla de los Libres", 
                  "Igualapa", "San Luis Acatlán", "Xochistlahuaca", "Acatepec", 
                  "Iliatenco", "Alcozauca de Guerrero", "Arcelia", "Cutzamala de Pinzón", 
                  "Coyuca de Catalán", "Pungarabato", "José Joaquín de Herrera", 
                  "Ahuacuotzingo", "San Miguel Totolapan", "Tlapehuala", "Pilcaya", 
                  "Zihuatanejo de Azueta", "Mochitlán", "Coyuca de Benítez", 
                  "Cualác", "Florencio Villarreal", "Huamuxtitlán", "Metepec", 
                  "Apan", "Acatlán", "Acaxochitlán", "Agua Blanca de Iturbide", 
                  "Alfajayucan", "Atlapexco", "Calnali", "Cardonal", "Chapulhuacán", 
                  "Epazoyucan", "Huautla", "Huehuetla", "Huejutla de Reyes", "Jacala de Ledezma", 
                  "Jaltocán", "Juárez Hidalgo", "San Agustín Metzquititlán", 
                  "Mineral del Monte", "Molango de Escamilla", "Nicolás Flores", 
                  "Omitlán de Juárez", "Pacula", "Pisaflores", "Mineral de la Reforma", 
                  "San Bartolo Tutotepec", "Santiago Tulantepec de Lugo Guerrero", 
                  "Tianguistengo", "Tlahuiltepa", "Tlanchinol", "Xochiatipan", 
                  "Xochicoatlán", "Zacualtipán de Ángeles", "Tlanalapa", "Tecozautla", 
                  "Eloxochitlán", "Metztitlán", "Huichapan", "Zempoala", "Tolcayuca", 
                  "Villa de Tezontepec", "Mixquiahuala de Juárez", "Tezontepec de Aldama", 
                  "Tlahuelilpan", "Tlaxcoapan", "Chapantongo", "Tula de Allende", 
                  "Tepetitlán", "El Arenal", "Chilcuautla", "Francisco I. Madero", 
                  "Progreso de Obregón", "San Salvador", "Zapotlán de Juárez", 
                  "Tetepango", "Tulancingo de Bravo", "Actopan", "Atotonilco el Grande", 
                  "Ixmiquilpan", "Lolotla", "La Misión", "San Felipe Orizatlán", 
                  "Santiago de Anaya", "Yahualica", "Emiliano Zapata", "Tepeapulco", 
                  "San Agustín Tlaxiaca", "Nopala de Villagrán", "Atotonilco de Tula", 
                  "Pachuca de Soto", "Ajacuba", "Almoloya", "Cuautepec de Hinojosa", 
                  "Huasca de Ocampo", "Huazalingo", "Mineral del Chico", "Singuilucan", 
                  "Tasquillo", "Tenango de Doria", "Tepehuacán de Guerrero", "Zimapán", 
                  "Tizayuca", "Tepeji del Río de Ocampo", "Atitalaquia", "Acatic", 
                  "Acatlán de Juárez", "Ahualulco de Mercado", "Amacueca", "Amatitán", 
                  "Ameca", "San Juanito de Escobedo", "Arandas", "El Arenal", "Atemajac de Brizuela", 
                  "Atengo", "Atenguillo", "Atotonilco el Alto", "Atoyac", "Autlán de Navarro", 
                  "Ayotlán", "Ayutla", "La Barca", "Bolaños", "Cabo Corrientes", 
                  "Casimiro Castillo", "Cihuatlán", "Zapotlán el Grande", "Cocula", 
                  "Colotlán", "Concepción de Buenos Aires", "Cuautitlán de García Barragán", 
                  "Cuautla", "Cuquío", "Chapala", "Chimaltitán", "Chiquilistlán", 
                  "Degollado", "Ejutla", "Encarnación de Díaz", "Etzatlán", 
                  "El Grullo", "Guachinango", "Guadalajara", "Hostotipaquillo", 
                  "Huejúcar", "Huejuquilla el Alto", "La Huerta", "Ixtlahuacán de los Membrillos", 
                  "Ixtlahuacán del Río", "Jalostotitlán", "Jamay", "Jesús María", 
                  "Jilotlán de los Dolores", "Jocotepec", "Juanacatlán", "Juchitlán", 
                  "Lagos de Moreno", "El Limón", "Magdalena", "Santa María del Oro", 
                  "La Manzanilla de la Paz", "Mascota", "Mazamitla", "Mexticacán", 
                  "Mezquitic", "Mixtlán", "Ocotlán", "Ojuelos de Jalisco", "Pihuamo", 
                  "Poncitlán", "Puerto Vallarta", "Villa Purificación", "Quitupan", 
                  "El Salto", "San Cristóbal de la Barranca", "San Diego de Alejandría", 
                  "San Juan de los Lagos", "San Julián", "San Marcos", "San Martín de Bolaños", 
                  "San Martín Hidalgo", "San Miguel el Alto", "Gómez Farías", 
                  "San Sebastián del Oeste", "Santa María de los Ángeles", "Sayula", 
                  "Tala", "Talpa de Allende", "Tamazula de Gordiano", "Tapalpa", 
                  "Tecalitlán", "Tecolotlán", "Techaluta de Montenegro", "Tenamaxtlán", 
                  "Teocaltiche", "Teocuitatlán de Corona", "Tepatitlán de Morelos", 
                  "Tequila", "Teuchitlán", "Tizapán el Alto", "Tlajomulco de Zúñiga", 
                  "San Pedro Tlaquepaque", "Tolimán", "Tomatlán", "Tonalá", 
                  "Tonaya", "Tonila", "Totatiche", "Tototlán", "Tuxcacuesco", 
                  "Tuxcueca", "Tuxpan", "Unión de San Antonio", "Unión de Tula", 
                  "Valle de Guadalupe", "Valle de Juárez", "San Gabriel", "Villa Corona", 
                  "Villa Guerrero", "Villa Hidalgo", "Cañadas de Obregón", "Yahualica de González Gallo", 
                  "Zacoalco de Torres", "Zapopan", "Zapotiltic", "Zapotitlán de Vadillo", 
                  "Zapotlán del Rey", "Zapotlanejo", "San Ignacio Cerro Gordo", 
                  "Aculco", "Almoloya del Río", "Acambay de Ruíz Castañeda", 
                  "Atizapán", "Almoloya de Alquisiras", "Almoloya de Juárez", 
                  "Amanalco", "Amatepec", "Atlacomulco", "Calimaya", "Capulhuac", 
                  "Coatepec Harinas", "Chapa de Mota", "Chapultepec", "Donato Guerra", 
                  "Ixtlahuaca", "Xalatlaco", "Isidro Fabela", "Ixtapan de la Sal", 
                  "Ixtapan del Oro", "Malinalco", "Metepec", "Mexicaltzingo", "Ocoyoacac", 
                  "Jilotepec", "Jilotzingo", "Jiquipilco", "Jocotitlán", "Joquicingo", 
                  "Lerma", "Otzoloapan", "Otzolotepec", "Polotitlán", "Morelos", 
                  "Nicolás Romero", "Ocuilan", "El Oro", "Rayón", "San Antonio la Isla", 
                  "San Felipe del Progreso", "San Mateo Atenco", "San Simón de Guerrero", 
                  "Santo Tomás", "Soyaniquilpan de Juárez", "Sultepec", "Tejupilco", 
                  "Temascalcingo", "Temascaltepec", "Texcalyacac", "Temoaya", "Tenancingo", 
                  "Tenango del Valle", "Tepotzotlán", "Texcaltitlán", "Tlatlaya", 
                  "Tianguistenco", "Timilpan", "Toluca", "Villa del Carbón", "Villa Guerrero", 
                  "Tonatico", "Valle de Bravo", "Villa de Allende", "Zacualpan", 
                  "Zumpahuacán", "Villa Victoria", "Xonacatlán", "Zinacantepec", 
                  "Zacazonapan", "Luvianos", "San José del Rincón", "Ixtapaluca", 
                  "Texcoco", "Tezoyuca", "Apaxco", "Atenco", "Jaltenco", "Juchitepec", 
                  "Melchor Ocampo", "Naucalpan de Juárez", "Tlalmanalco", "Atizapán de Zaragoza", 
                  "Tlalnepantla de Baz", "Nezahualcóyotl", "Nextlalpan", "Tultepec", 
                  "Cuautitlán Izcalli", "Atlautla", "Nopaltepec", "Zumpango", 
                  "Otumba", "Valle de Chalco Solidaridad", "Tonanitla", "Tultitlán", 
                  "Axapusco", "Ayapango", "Ozumba", "Papalotla", "Coacalco de Berriozábal", 
                  "Cocotitlán", "Coyotepec", "La Paz", "Cuautitlán", "Chalco", 
                  "Chiautla", "San Martín de las Pirámides", "Tecámac", "Temamatla", 
                  "Chicoloapan", "Chiconcuac", "Ecatzingo", "Temascalapa", "Tenango del Aire", 
                  "Chimalhuacán", "Teoloyucan", "Teotihuacán", "Ecatepec de Morelos", 
                  "Hueypoxtla", "Tepetlaoxtoc", "Huehuetoca", "Tepetlixpa", "Tequixquiac", 
                  "Huixquilucan", "Acolman", "Amecameca", "Zamora", "Tangancícuaro", 
                  "Aquila", "Arteaga", "Tumbiscatío", "San Lucas", "Huetamo", 
                  "Chinicuila", "Aguililla", "Múgica", "Turicato", "Carácuaro", 
                  "Tepalcatepec", "Nocupétaro", "Nuevo Urecho", "Ario", "Susupuato", 
                  "Tiquicheo de Nicolás Romero", "Juárez", "Buenavista", "Tuzantla", 
                  "Ziracuaretiro", "Nuevo Parangaricutiro", "Tancítaro", "Jungapeo", 
                  "Acuitzio", "Peribán", "Tingambato", "Ocampo", "Tuxpan", "Tzintzuntzan", 
                  "Angangueo", "Erongarícuaro", "Nahuatzen", "Quiroga", "Charo", 
                  "Cherán", "Los Reyes", "Queréndaro", "Tocumbo", "Hidalgo", 
                  "Tarímbaro", "Tingüindín", "Cotija", "Zinapécuaro", "Huaniqueo", 
                  "Chucándiro", "Copándaro", "Jiménez", "Purépero", "Tangamandapio", 
                  "Morelos", "Cuitzeo", "Santa Ana Maya", "Jiquilpan", "Tlazazalca", 
                  "Panindícuaro", "Chavinda", "Cojumatlán de Régules", "Angamacutiro", 
                  "Ixtlán", "Churintzio", "Epitacio Huerta", "Zináparo", "Ecuandureo", 
                  "Puruándiro", "Numarán", "Vista Hermosa", "Tanhuato", "La Piedad", 
                  "Salvador Escalante", "Lázaro Cárdenas", "Coahuayana", "Churumuco", 
                  "Coalcomán de Vázquez Pallares", "La Huacana", "Apatzingán", 
                  "Parácuaro", "Gabriel Zamora", "Taretan", "Tacámbaro", "Indaparapeo", 
                  "Chilchota", "Madero", "Zitácuaro", "Huiramba", "Pátzcuaro", 
                  "Lagunillas", "Tzitzio", "Aporo", "Paracho", "Irimbo", "Charapan", 
                  "Senguio", "Morelia", "Tlalpujahua", "Coeneo", "Álvaro Obregón", 
                  "Zacapu", "Jacona", "Maravatío", "Huandacareo", "Contepec", 
                  "Villamar", "Marcos Castellanos", "Sahuayo", "Penjamillo", "Venustiano Carranza", 
                  "Pajacuarán", "Briseñas", "José Sixto Verduzco", "Yurécuaro", 
                  "Uruapan"))

muns$NOM_MUN<-Nombres

leafmap=merge(muns, 
              data, 
              by.x = "inegi", 
              by.y = "clave",                    
              sort = FALSE)
leafmap.sub <- subset(leafmap, crec_Y != "NA")
w<-poly2nb(leafmap.sub)
xy<-coordinates(leafmap)
#Para el indice
listw <-  nb2listw(w, style='B')
moran.test(leafmap.sub$crec_Y,listw,na.action = na.exclude)
moran.test(leafmap.sub$gap_edu05,listw,na.action = na.exclude)
moran.test(leafmap.sub$gini0505,listw,na.action = na.exclude)

#Para el mapa con crecimiento
local <- localmoran(x = leafmap.sub$crec_Y,listw)
local2<-localmoran(x = leafmap.sub$gap_edu05,listw)
local3<-localmoran(x = leafmap.sub$gini0505,listw,na.action = na.exclude)
moran.map <- cbind(leafmap.sub, local,local2,local3)


m.crec <- leafmap.sub$crec_Y - mean(leafmap.sub$crec_Y)
m.gap<- leafmap.sub$gap_edu05 - mean(leafmap.sub$gap_edu05)
m.gin<- leafmap.sub$gini0505 - mean(leafmap.sub$gini0505)
m.local <- local[,1] - mean(local[,1])
m.local2<- local2[,1] - mean(local2[,1])
m.local3<- local3[,1] - mean(local3[,1])

signif <- 0.1

quadrant <- vector(mode="numeric",length=nrow(local))
quadrant[local[,5]<signif] <- "Significativo"
quadrant[local[,5]>signif] <- "No significativo"
moran.map$cuad<-quadrant

quadrant2 <- vector(mode="numeric",length=nrow(local))
quadrant2[local2[,5]<signif] <- "Significativo"
quadrant2[local2[,5]>signif] <- "No significativo"
moran.map$cuad2<-quadrant2

quadrant3 <- vector(mode="numeric",length=nrow(local))
quadrant3[local2[,5]<signif] <- "Significativo"
quadrant3[local2[,5]>signif] <- "No significativo"
moran.map$cuad3<-quadrant3

m <- leaflet(moran.map) %>%
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN')))

labels <- sprintf(
  "<strong>%s</strong><br/>%g Estadistico",
  moran.map$NOM_MUN,moran.map$Ii
) %>% lapply(htmltools::HTML)
labels1 <- sprintf(
  "<strong>%s</strong><br/>%g Estadistico",
  moran.map$NOM_MUN,moran.map$Ii.1
) %>% lapply(htmltools::HTML)
labels2 <- sprintf(
  "<strong>%s</strong><br/>%g Estadistico",
  moran.map$NOM_MUN,moran.map$Ii.2
) %>% lapply(htmltools::HTML)

pal2<-colorFactor("BrBG", domain = moran.map$cuad)
pal3<-colorFactor("PiYG", domain = moran.map$cuad2)
pal4<-colorFactor("PuOr", domain = moran.map$cuad3)


n <- m %>% addPolygons(
  fillColor = ~pal2(cuad),
  weight = 2,
  opacity = 1,
  color = "gray",
  dashArray = "3",
  fillOpacity = 0.8,
  highlight = highlightOptions(
    weight = 5,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
  label = labels,
  labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto"),group = "Crecimiento") %>% addPolygons(
      fillColor = ~pal3(cuad2),
      weight = 2,
      opacity = 1,
      color = "gray",
      dashArray = "3",
      fillOpacity = 0.8,
      highlight = highlightOptions(
        weight = 5,
        color = "#666",
        dashArray = "",
        fillOpacity = 0.7,
        bringToFront = TRUE),
      label = labels1,
      labelOptions = labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto"),group = "Brecha") %>% addPolygons(
          fillColor = ~pal4(cuad3),
          weight = 2,
          opacity = 1,
          color = "gray",
          dashArray = "3",
          fillOpacity = 0.8,
          highlight = highlightOptions(
            weight = 5,
            color = "#666",
            dashArray = "",
            fillOpacity = 0.7,
            bringToFront = TRUE),
          label = labels2,
          labelOptions = labelOptions(
            style = list("font-weight" = "normal", padding = "3px 8px"),
            textsize = "15px",
            direction = "auto"),group = "Gini")


Moran <- n%>%
  addProviderTiles(providers$OpenStreetMap.HOT) %>%
  addMiniMap() %>% addLegend(pal = pal2, values = ~cuad, opacity = 0.7, title = "Grado de significancia",
                             position = "bottomright",group = "Crecimiento") %>% 
  addLegend(pal = pal3, values = ~cuad2, opacity = 0.7, title = "Grado de significancia",
                                                                     position = "bottomright",group = "Brecha")%>% 
  addLegend(pal = pal4, values = ~cuad3, opacity = 0.7, title = "Grado de significancia",
                                                                                                            position = "bottomright",group = "Gini")%>%
  addLayersControl(
    baseGroups = c("Crecimiento", "Gini","Brecha")) %>% hideGroup(c("Gini","Brecha"))

library(htmlwidgets)
saveWidget(Moran, file = paste0(inout, "/moran.html"), selfcontained = F)

